export const doctorDataList = [
  {
    id: 1,
    name: 'Dr. Ana Popescu',
    clinicName: 'MediClinic',
    speciality: 'Alergologie si Imunologie',
  },
  {
    id: 2,
    name: 'Dr. Stefan Andrei',
    clinicName: 'HealthPoint',
    speciality: 'Alergologie si Imunologie',
  },
  {
    id: 3,
    name: 'Dr. Maria Ionescu',
    clinicName: 'Medicare Center',
    speciality: 'Alergologie si Imunologie',
  },
  {
    id: 4,
    name: 'Dr. Ion Dumitrescu',
    clinicName: 'PathoLab',
    speciality: 'Anatomie patologica',
  },
  {
    id: 5,
    name: 'Dr. Elena Stanescu',
    clinicName: 'HealthLab',
    speciality: 'Anatomie patologica',
  },
  {
    id: 6,
    name: 'Dr. Vlad Radulescu',
    clinicName: 'LabMed',
    speciality: 'Anatomie patologica',
  },
  {
    id: 7,
    name: 'Dr. Andrei Popa',
    clinicName: 'CardioCare',
    speciality: 'Cardiologie',
  },
  {
    id: 8,
    name: 'Dr. Ioana Marinescu',
    clinicName: 'HeartClinic',
    speciality: 'Cardiologie',
  },
  {
    id: 9,
    name: 'Dr. Mihaela Georgescu',
    clinicName: 'Heartbeat Hospital',
    speciality: 'Cardiologie',
  },
  {
    id: 10,
    name: 'Dr. Mihai Popescu',
    clinicName: 'Surgery Center',
    speciality: 'Chirurgie',
  },
  {
    id: 11,
    name: 'Dr. Laura Radu',
    clinicName: 'SurgiMed',
    speciality: 'Chirurgie',
  },
  {
    id: 12,
    name: 'Dr. Daniel Ionescu',
    clinicName: 'MediSurg',
    speciality: 'Chirurgie',
  },
  {
    id: 13,
    name: 'Dr. Andreea Voicu',
    clinicName: 'DietClinic',
    speciality: 'Dietetica',
  },
  {
    id: 14,
    name: 'Dr. Cristian Petrescu',
    clinicName: 'NutriHealth',
    speciality: 'Dietetica',
  },
  {
    id: 15,
    name: 'Dr. Alexandra Ion',
    clinicName: 'HealthyEating Clinic',
    speciality: 'Dietetica',
  },
  {
    id: 16,
    name: 'Dr. Ionut Radulescu',
    clinicName: 'EpiCare',
    speciality: 'Epidemiologie',
  },
  {
    id: 17,
    name: 'Dr. Elena Vasilescu',
    clinicName: 'EpidemioLab',
    speciality: 'Epidemiologie',
  },
  {
    id: 18,
    name: 'Dr. Ana Maria Popa',
    clinicName: 'HealthWatch Clinic',
    speciality: 'Epidemiologie',
  },
  {
    id: 19,
    name: 'Dr. Victor Andreescu',
    clinicName: 'GeneLab',
    speciality: 'Genetica medicala',
  },
  {
    id: 20,
    name: 'Dr. Diana Moldovan',
    clinicName: 'GeneMed',
    speciality: 'Genetica medicala',
  },
  {
    id: 21,
    name: 'Dr. Catalin Popescu',
    clinicName: 'DNA Clinic',
    speciality: 'Genetica medicala',
  },
];
