export const doctorDataList = [
  {
    id: 1,
    name: 'Dr. Ana Popescu',
    clinicName: 'MediClinic',
    speciality: 'Alergologie si Imunologie',
  },
  {
    id: 2,
    name: 'Dr. Stefan Andrei',
    clinicName: 'HealthPoint',
    speciality: 'Alergologie si Imunologie',
  },
  {
    id: 3,
    name: 'Dr. Maria Ionescu',
    clinicName: 'Medicare Center',
    speciality: 'Alergologie si Imunologie',
  },
  {
    id: 4,
    name: 'Dr. Ion Dumitrescu',
    clinicName: 'PathoLab',
    speciality: 'Anatomie patologica',
  },
  {
    id: 5,
    name: 'Dr. Elena Stanescu',
    clinicName: 'HealthLab',
    speciality: 'Anatomie patologica',
  },
  {
    id: 6,
    name: 'Dr. Vlad Radulescu',
    clinicName: 'LabMed',
    speciality: 'Anatomie patologica',
  },
  {
    id: 7,
    name: 'Dr. Andrei Popa',
    clinicName: 'CardioCare',
    speciality: 'Cardiologie',
  },
  {
    id: 8,
    name: 'Dr. Ioana Marinescu',
    clinicName: 'HeartClinic',
    speciality: 'Cardiologie',
  },
  {
    id: 9,
    name: 'Dr. Mihaela Georgescu',
    clinicName: 'Heartbeat Hospital',
    speciality: 'Cardiologie',
  },
  {
    id: 10,
    name: 'Dr. Mihai Popescu',
    clinicName: 'Surgery Center',
    speciality: 'Chirurgie',
  },
  {
    id: 11,
    name: 'Dr. Laura Radu',
    clinicName: 'SurgiMed',
    speciality: 'Chirurgie',
  },
  {
    id: 12,
    name: 'Dr. Daniel Ionescu',
    clinicName: 'MediSurg',
    speciality: 'Chirurgie',
  },
  {
    id: 13,
    name: 'Dr. Andreea Voicu',
    clinicName: 'DietClinic',
    speciality: 'Dietetica',
  },
  {
    id: 14,
    name: 'Dr. Cristian Petrescu',
    clinicName: 'NutriHealth',
    speciality: 'Dietetica',
  },
  {
    id: 15,
    name: 'Dr. Alexandra Ion',
    clinicName: 'HealthyEating Clinic',
    speciality: 'Dietetica',
  },
  {
    id: 16,
    name: 'Dr. Ionut Radulescu',
    clinicName: 'EpiCare',
    speciality: 'Epidemiologie',
  },
  {
    id: 17,
    name: 'Dr. Elena Vasilescu',
    clinicName: 'EpidemioLab',
    speciality: 'Epidemiologie',
  },
  {
    id: 18,
    name: 'Dr. Ana Maria Popa',
    clinicName: 'HealthWatch Clinic',
    speciality: 'Epidemiologie',
  },
  {
    id: 19,
    name: 'Dr. Victor Andreescu',
    clinicName: 'GeneLab',
    speciality: 'Genetica medicala',
  },
  {
    id: 20,
    name: 'Dr. Diana Moldovan',
    clinicName: 'GeneMed',
    speciality: 'Genetica medicala',
  },
  {
    id: 21,
    name: 'Dr. Catalin Popescu',
    clinicName: 'DNA Clinic',
    speciality: 'Genetica medicala',
  },
  {
    id: 22,
    name: 'Dr. Maria Popescu',
    clinicName: 'PneumoClinic',
    speciality: 'Pneumologie',
  },
  {
    id: 23,
    name: 'Dr. Andrei Ionescu',
    clinicName: 'LungCare Center',
    speciality: 'Pneumologie',
  },
  {
    id: 24,
    name: 'Dr. Elena Stan',
    clinicName: 'PulmoHealth',
    speciality: 'Pneumologie',
  },
  {
    id: 25,
    name: 'Dr. Ion Popa',
    clinicName: 'NeuroClinic',
    speciality: 'Neurologie',
  },
  {
    id: 26,
    name: 'Dr. Ana Georgescu',
    clinicName: 'BrainCare Center',
    speciality: 'Neurologie',
  },
  {
    id: 27,
    name: 'Dr. Vlad Ionut',
    clinicName: 'NeuroHealth',
    speciality: 'Neurologie',
  },
  {
    id: 28,
    name: 'Dr. Andreea Pop',
    clinicName: 'Ophthalmology Clinic',
    speciality: 'Oftalmologie',
  },
  {
    id: 29,
    name: 'Dr. Cristian Marinescu',
    clinicName: 'EyeCare Center',
    speciality: 'Oftalmologie',
  },
  {
    id: 30,
    name: 'Dr. Mihaela Vasile',
    clinicName: 'VisionHealth',
    speciality: 'Oftalmologie',
  },
  {
    id: 31,
    name: 'Dr. Laura Radu',
    clinicName: 'Radiology Center',
    speciality: 'Radiologie',
  },
  {
    id: 32,
    name: 'Dr. Stefan Popescu',
    clinicName: 'X-Ray Lab',
    speciality: 'Radiologie',
  },
  {
    id: 33,
    name: 'Dr. Diana Stanescu',
    clinicName: 'Radiant Health',
    speciality: 'Radiologie',
  },
  {
    id: 34,
    name: 'Dr. Ionut Ionescu',
    clinicName: 'StomatoClinic',
    speciality: 'Stomatologie',
  },
  {
    id: 35,
    name: 'Dr. Alexandra Popa',
    clinicName: 'DentalCare Center',
    speciality: 'Stomatologie',
  },
  {
    id: 36,
    name: 'Dr. Mihai Andrei',
    clinicName: 'OralHealth',
    speciality: 'Stomatologie',
  },
  {
    id: 37,
    name: 'Dr. Ana Maria Pop',
    clinicName: 'UroClinic',
    speciality: 'Urologie',
  },
  {
    id: 38,
    name: 'Dr. Vlad Ionescu',
    clinicName: 'UroCare Center',
    speciality: 'Urologie',
  },
  {
    id: 39,
    name: 'Dr. Elena Popescu',
    clinicName: 'UroHealth',
    speciality: 'Urologie',
  },
  {
    id: 40,
    name: 'Dr. Ionut Pop',
    clinicName: 'PsychiCare Clinic',
    speciality: 'Psihiatrie',
  },
  {
    id: 41,
    name: 'Dr. Maria Vlad',
    clinicName: 'Mental Health Center',
    speciality: 'Psihiatrie',
  },
  {
    id: 42,
    name: 'Dr. Andrei Vasile',
    clinicName: 'MindCare',
    speciality: 'Psihiatrie',
  },
  { id: 43, name: 'Dr. Ana Popa', clinicName: 'ENT Clinic', speciality: 'ORL' },
  {
    id: 44,
    name: 'Dr. Catalin Stan',
    clinicName: 'EarNoseThroat Center',
    speciality: 'ORL',
  },
  {
    id: 45,
    name: 'Dr. Andreea Ionescu',
    clinicName: 'HearingHealth',
    speciality: 'ORL',
  },
  {
    id: 46,
    name: 'Dr. Maria Pop',
    clinicName: 'GynaeClinic',
    speciality: 'Ginecologie',
  },
  {
    id: 47,
    name: 'Dr. Vlad Stefan',
    clinicName: 'WomenCare Center',
    speciality: 'Ginecologie',
  },
  {
    id: 48,
    name: 'Dr. Elena Ana',
    clinicName: 'FemHealth',
    speciality: 'Ginecologie',
  },
  {
    id: 49,
    name: 'Dr. Ion Popescu',
    clinicName: 'FamilyMed Clinic',
    speciality: 'Medicină de familie',
  },
  {
    id: 50,
    name: 'Dr. Mihaela Ionescu',
    clinicName: 'FamilyCare Center',
    speciality: 'Medicină de familie',
  },
  {
    id: 51,
    name: 'Dr. Andrei Vlad',
    clinicName: 'HealthyFam',
    speciality: 'Medicină de familie',
  },
  {
    id: 52,
    name: 'Dr. Ana Maria Ionescu',
    clinicName: 'Pediatric Clinic',
    speciality: 'Pediatrie',
  },
  {
    id: 53,
    name: 'Dr. Stefan Andrei',
    clinicName: 'ChildCare Center',
    speciality: 'Pediatrie',
  },
  {
    id: 54,
    name: 'Dr. Maria Elena',
    clinicName: 'KidsHealth',
    speciality: 'Pediatrie',
  },
  {
    id: 55,
    name: 'Dr. Catalin Popa',
    clinicName: 'Psychology Clinic',
    speciality: 'Psihologie',
  },
  {
    id: 56,
    name: 'Dr. Elena Maria',
    clinicName: 'MindWellness',
    speciality: 'Psihologie',
  },
  {
    id: 57,
    name: 'Dr. Vlad Ionescu',
    clinicName: 'PsychoCare',
    speciality: 'Psihologie',
  },
  {
    id: 58,
    name: 'Dr. Ionut Popescu',
    clinicName: 'OrthoClinic',
    speciality: 'Ortopedie',
  },
  {
    id: 59,
    name: 'Dr. Andreea Maria',
    clinicName: 'OrthoCare Center',
    speciality: 'Ortopedie',
  },
  {
    id: 60,
    name: 'Dr. Maria Elena',
    clinicName: 'OrthoHealth',
    speciality: 'Ortopedie',
  },
];
